// Consolidate rigid architectural parts by material to reduce draw calls.
function bake(parent){parent.updateWorldMatrix(true,true);const inverse=parent.matrixWorld.clone().invert(),groups=new Map(),remove=[];parent.traverse(child=>{if(!child.isMesh||child.isInstancedMesh||Array.isArray(child.material)||child.material.isMeshBasicMaterial)return;const geo=child.geometry.index?child.geometry.toNonIndexed():child.geometry.clone();geo.applyMatrix4(inverse.clone().multiply(child.matrixWorld));let entry=groups.get(child.material);if(!entry){entry={position:[],normal:[],uv:[]};groups.set(child.material,entry);}for(const name of ['position','normal','uv']){const a=geo.getAttribute(name);if(a)for(const n of a.array)entry[name].push(n);}geo.dispose();remove.push(child);});remove.forEach(m=>{m.parent.remove(m);m.geometry.dispose();});for(const [mat,attrs] of groups){const geo=new T.BufferGeometry();for(const name of ['position','normal','uv'])if(attrs[name].length)geo.setAttribute(name,new T.Float32BufferAttribute(attrs[name],name==='uv'?2:3));geo.computeBoundingSphere();const mesh=new T.Mesh(geo,mat);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);}}
[deck,structural,...rooms,dishBase,rover].forEach(bake);
const initial=[0,1,2,3,4,5,6,7],presets={swap:[1,0,2,3,4,5,6,7],science:[0,1,5,7,2,3,4,6],service:[6,1,2,3,4,5,0,7]},taskNames={swap:'舱段换位',science:'科研协作',service:'维护调度',custom:'自定义布局'};
let moves=[],phases=[],duration=0,time=0,playing=false,estop=false,task='swap',events=[],routeKey='',cutaway=false,explosion=0,lastNow=performance.now(),toastTimer=null,ready=false;
let yaw=.52,pitch=.63,distance=1510,target=new T.Vector3(20,15,10),goal={yaw:.52,pitch:.63,distance:1510,target:new T.Vector3(20,15,10)},viewName='overview';
const mobile=()=>stage.clientWidth<620;const overviewDistance=()=>mobile()?1870:1510;
distance=goal.distance=overviewDistance();
const notify=(message,bad=false)=>{clearTimeout(toastTimer);$('toast').textContent=message;$('toast').classList.toggle('bad',bad);$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,bad?7000:3500);};
const audit=(event,detail)=>events.push({event,time:+time.toFixed(2),detail});const fmt=t=>`${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`;
$('target').innerHTML=initial.map((_,i)=>`<label>P${i+1}<select aria-label="位置P${i+1}的目标舱段">${initial.map(r=>`<option value="${r}">R${r+1}</option>`).join('')}</select></label>`).join('');
const selects=[...$('target').querySelectorAll('select')];const selected=()=>selects.map(s=>+s.value);const setTarget=a=>selects.forEach((s,i)=>s.value=a[i]);
function controls(){$('play').textContent=!ready?'暂无任务':estop?'解除急停':playing?'暂停演示':time>=duration&&duration?'再次演示':time>0?'继续演示':'开始演示';$('play').disabled=!ready||!phases.length;$('timeline').disabled=!ready||!phases.length||estop;$('replay').disabled=!ready||!phases.length;$('export').disabled=!ready;}
function chooseView(name){viewName=name;cutaway=name==='mechanism';if(cutaway){playing=false;controls();}const st=C.state(initial,phases,time),r=st.active>=0?st.active:0,p=st.positions[r];if(name==='closeup'){goal={yaw:.22,pitch:.44,distance:470,target:new T.Vector3(p[0]-400,38,300-p[1])};}else if(name==='topview'){goal={yaw:0,pitch:1.48,distance:mobile()?1570:1220,target:new T.Vector3(0,10,0)};}else{goal={yaw:.52,pitch:name==='mechanism'?.4:.63,distance:overviewDistance(),target:new T.Vector3(20,name==='mechanism'?65:15,10)};}for(const id of ['overview','closeup','topview','mechanism']){$(id).classList.toggle('active',id===name);$(id).setAttribute('aria-pressed',String(id===name));}}
function compile(targetValues,auto=true){playing=false;estop=false;time=0;events=[];task=task||'custom';try{const blocked=$('block').checked?[[360,270,440,330]]:[];moves=C.plan(initial,targetValues,blocked);const tl=C.timeline(moves,80);phases=tl.phases;duration=tl.duration;ready=true;$('timeline').max=duration||1;$('moveCount').textContent=moves.length;$('total').textContent=moves.length;$('distance').textContent=(moves.reduce((s,m)=>s+C.length(m.path),0)/1000).toFixed(2)+' m';$('log').innerHTML=moves.map(m=>`<li>${buildingNames[m.room]} · ${m.from===8?'W':'P'+(m.from+1)} → ${m.to===8?'W':'P'+(m.to+1)}</li>`).join('')||'<li>目标布局已满足</li>';playing=auto&&moves.length>0;audit('plan',{task,target:targetValues,blocked,velocity:80});chooseView('overview');controls();if(!moves.length)notify('当前布局已满足目标，无需搬运。');}catch(e){moves=[];phases=[];duration=0;ready=false;$('timeline').max=1;$('moveCount').textContent='—';$('total').textContent='—';$('log').textContent='未能生成有效计划。';notify(e.message,true);controls();}}
document.querySelectorAll('[data-task]').forEach(button=>button.onclick=()=>{task=button.dataset.task;setTarget(presets[task]);document.querySelectorAll('[data-task]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button));});compile(presets[task],true);});
$('play').onclick=()=>{if(!ready)return;if(time>=duration)time=0;if(estop){estop=false;notify('急停已解除，继续演示。');}playing=!playing;if(playing&&cutaway)chooseView('overview');audit(playing?'play':'pause');controls();};
$('replay').onclick=()=>{time=0;estop=false;playing=true;if(cutaway)chooseView('overview');audit('restart');controls();};
$('timeline').oninput=e=>{if(estop)return;playing=false;time=+e.target.value;audit('seek');controls();};
for(const id of ['overview','closeup','topview','mechanism'])$(id).onclick=()=>chooseView(id);
let focusBefore=null;function openSettings(){focusBefore=document.activeElement;$('settings').hidden=false;$('closeSettings').focus();}function closeSettings(){$('settings').hidden=true;focusBefore?.focus();}
$('openSettings').onclick=openSettings;$('closeSettings').onclick=closeSettings;$('settings').onclick=e=>{if(e.target===$('settings'))closeSettings();};
$('apply').onclick=()=>{task='custom';document.querySelectorAll('[data-task]').forEach(b=>{b.classList.remove('active');b.setAttribute('aria-pressed','false');});compile(selected(),true);if(ready)closeSettings();};
$('block').onchange=()=>{compile(selected(),false);if(ready)notify($('block').checked?'已根据封闭区重新规划，点击开始演示。':'通道已恢复，计划已更新。');};
$('stop').onclick=()=>{playing=false;estop=true;audit('emergency-stop');controls();closeSettings();notify('已暂停所有动作。点击“解除急停”恢复。',true);};
$('presentation').onclick=()=>{document.body.classList.add('reduced');$('exitImmersion').hidden=false;notify('已进入沉浸展示。按 Esc 退出，空格播放或暂停。');resize();};
$('exitImmersion').onclick=()=>{document.body.classList.remove('reduced');$('exitImmersion').hidden=true;resize();};
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('settings').hidden)closeSettings();else{$('exitImmersion').click();}}if(e.code==='Space'&&$('settings').hidden&&!['SELECT','INPUT','BUTTON'].includes(document.activeElement.tagName)){e.preventDefault();$('play').click();}if(e.key==='Tab'&&!$('settings').hidden){const items=[...$('settings').querySelectorAll('button:not(:disabled),input,select')],first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
// Touch and mouse share orbit controls; two fingers adjust zoom.
const pointers=new Map();let dragStart=null,pinch=0;
renderer.domElement.addEventListener('pointerdown',e=>{pointers.set(e.pointerId,[e.clientX,e.clientY]);dragStart=[e.clientX,e.clientY];renderer.domElement.setPointerCapture(e.pointerId);});
renderer.domElement.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,[e.clientX,e.clientY]);if(pointers.size===2){const [a,b]=[...pointers.values()],d=Math.hypot(a[0]-b[0],a[1]-b[1]);if(pinch)goal.distance=Math.max(250,Math.min(2700,goal.distance*pinch/d));pinch=d;}else if(dragStart){goal.yaw-=(e.clientX-dragStart[0])*.005;goal.pitch=Math.max(.12,Math.min(1.5,goal.pitch+(e.clientY-dragStart[1])*.004));}dragStart=[e.clientX,e.clientY];});for(const event of ['pointerup','pointercancel'])renderer.domElement.addEventListener(event,e=>{pointers.delete(e.pointerId);pinch=0;dragStart=null;});renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();goal.distance=Math.max(250,Math.min(2700,goal.distance*Math.exp(e.deltaY*.001)));},{passive:false});
$('export').onclick=()=>{const data={version:'2.0',display:'LUNARIS architectural concept',scope:'geometry-and-sequence-only',target:events.find(e=>e.event==='plan').detail.target,initial,moves,phases,predictedSeconds:duration,events,current:C.state(initial,phases,time),blocked:$('block').checked,velocityMmPerSec:80};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='LUNARIS-simulation.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
const phaseText={ready:'已就绪',position:'共享机构定位',pick:'建立磁吸牵引',drag:'舱段移动中',drop:'舱段就位',return:'共享机构返回',done:'重构完成'};
function draw(dt){const st=C.state(initial,phases,time),w=stage.clientWidth,h=stage.clientHeight;explosion+=(Number(cutaway)-explosion)*Math.min(1,dt*6);deck.position.y=explosion*95;obstruction.position.y=explosion*95;obstruction.visible=$('block').checked;bridge.position.z=300-st.head[1];carriage.position.x=st.head[0]-400;magnet.position.y=24+st.lift*2;
 rooms.forEach((g,i)=>{g.position.set(st.positions[i][0]-400,32+explosion*95,300-st.positions[i][1]);g.userData.marker.visible=i===st.active&&!cutaway;});
 const ph=phases.find(p=>time>=p.start&&time<p.end),m=moves[Math.min(st.finished,moves.length-1)],key=st.active>=0&&m?JSON.stringify(m.path):'';if(key!==routeKey){if(routeLine){station.remove(routeLine);routeLine.geometry.dispose();routeLine.material.dispose();routeLine=null;}if(key)routeLine=line(station,m.path.map(([x,y])=>[x-400,32,300-y]),'#dfc396',.8);routeKey=key;}if(routeLine){routeLine.position.y=explosion*95;routeLine.visible=!cutaway;}
 if(viewName==='closeup'&&playing&&st.active>=0){goal.target.set(st.head[0]-400,38,300-st.head[1]);}
 const ease=Math.min(1,dt*5);yaw+=(goal.yaw-yaw)*ease;pitch+=(goal.pitch-pitch)*ease;distance+=(goal.distance-distance)*ease;target.lerp(goal.target,ease);const dist=distance*Math.max(1,.86/camera.aspect);camera.position.set(target.x+Math.sin(yaw)*Math.cos(pitch)*dist,target.y+Math.sin(pitch)*dist,target.z+Math.cos(yaw)*Math.cos(pitch)*dist);camera.lookAt(target);camera.updateMatrixWorld();
 const labelsEnabled=$('labels').checked;rooms.forEach((g,i)=>{const label=g.userData.label,v=new T.Vector3(g.position.x,g.position.y+56,g.position.z).project(camera),screenX=(v.x+1)*w/2,screenY=(1-v.y)*h/2;label.hidden=!labelsEnabled||v.z>1||v.z< -1||screenX<45||screenX>w-45||screenY<65||screenY>h-45||(mobile()&&i!==st.active&&i!==0&&i!==7);if(!label.hidden){label.style.left=screenX+'px';label.style.top=screenY+'px';label.classList.toggle('active',i===st.active);}});
 $('phase').textContent=estop?'已急停':cutaway?'机构剖视 · 搬运已暂停':!ready?'请在更多中检查目标布局':`${taskNames[task]} · ${time===0?'已就绪':phaseText[st.type]}`;$('time').textContent=`${fmt(time)} / ${fmt(duration)}`;$('timeline').value=time;$('completed').textContent=st.finished;
 $('detail').textContent=cutaway?'面板抬起以展示共享 XY 机构；这不是舱段垂直搬运。':estop?'所有动作保持当前状态，解除急停后继续。':time===0?'点开始或直接选择任务，即可观看建筑换位。':st.type==='done'?'目标布局已达成，等待区重新空闲。':`${st.active>=0?buildingNames[st.active]+' · ':''}${phaseText[st.type]}${m&&st.active>=0?' · '+(m.from===8?'等待区':'P'+(m.from+1))+' → '+(m.to===8?'等待区':'P'+(m.to+1)):''}`;
 renderer.render(scene,camera);
}
function resize(){const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(stage);resize();
document.addEventListener('visibilitychange',()=>{if(document.hidden){playing=false;controls();}lastNow=performance.now();});
setTarget(presets.swap);compile(presets.swap,false);
function frame(now){const dt=Math.min(.05,Math.max(.001,(now-lastNow)/1000));lastNow=now;if(playing){time+=dt*+$('speed').value;if(time>=duration){time=duration;playing=false;audit('complete');if($('loop').checked){time=0;playing=true;audit('loop');}controls();}}draw(dt);requestAnimationFrame(frame);}requestAnimationFrame(frame);
})();
