  const C=window.LunarCore,initial=[0,1,2,3,4,5,6,7];
  const presets={swap:[1,0,2,3,4,5,6,7],science:[0,1,5,7,2,3,4,6],service:[6,1,2,3,4,5,0,7]};
  let moves=[],phases=[],duration=0,time=0,playing=false,estop=false,planned=false,events=[],lastPhase='',last=performance.now(),yaw=.8,pitch=.68,distance=1730;
  const obstacle=new T.Group();model.add(obstacle);box(obstacle,80,3,60,0,103,0,M('#c66b48',{transparent:true,opacity:.65}),false);obstacle.visible=false;
  // Replace decorative campus tracks with a lunar station parking plan.
  cx.clearRect(0,0,800,600);cx.setLineDash([4,5]);cx.strokeStyle='#97aca0';cx.lineWidth=1;
  for(const y of [120,300,480])path([[80,y],[720,y]]);
  for(const x of [80,160,240,320,400,480,560,640,720])path([[x,120],[x,480]]);
  cx.setLineDash([]);cx.font='12px Microsoft YaHei';cx.textAlign='center';cx.fillStyle='#47634f';
  C.slots.forEach(([x,y],i)=>{cx.strokeRect(x-40,600-y-30,80,60);cx.fillText(i===8?'等待区 W':'P'+(i+1),x,600-y-37);});cx.textAlign='left';cx.fillText('LUNAR STATION / SHARED XY DRIVE',28,30);trackTex.needsUpdate=true;
  rooms.forEach((r,i)=>{r.children[1].material.color.set(['#426d89','#6689a0','#b08b63','#c2a47e','#c69b40','#608475','#ab6256','#777a9b'][i]);});
  const names=['实验 A','实验 B','生活 A','生活 B','能源','物资','维护','通信'];
  $('target').innerHTML=C.slots.slice(0,8).map((_,i)=>`<label>P${i+1}<select aria-label="位置 P${i+1} 的目标舱段" data-slot="${i}">${names.map((n,r)=>`<option value="${r}">R${r+1} ${n}</option>`).join('')}</select></label>`).join('');
  const selects=[...$('target').querySelectorAll('select')];const setTarget=a=>selects.forEach((s,i)=>s.value=a[i]);setTarget(presets.swap);
  const note=(text,bad=false)=>{$('notice').textContent=text;$('notice').classList.toggle('bad',bad);};
  function audit(type,detail){events.push({event:type,simulationSeconds:+time.toFixed(3),detail});}
  function invalidate(){playing=false;planned=false;estop=false;moves=[];phases=[];duration=0;time=0;events=[];$('moves').textContent='—';$('distance').textContent='—';$('estimate').textContent='—';$('log').innerHTML='<li>配置已变更，请重新规划</li>';$('timeline').max=1;controls();draw();}
  function controls(){$('play').textContent=playing?'暂停':estop?'解除急停并继续':'播放';for(const id of ['play','step','stop','export'])$(id).disabled=!planned||!phases.length;$('timeline').disabled=!planned||!phases.length;}
  function compile(){invalidate();try{const target=selects.map(s=>+s.value),blocked=$('block').checked?[[360,270,440,330]]:[];moves=C.plan(initial,target,blocked);const tl=C.timeline(moves,+$('velocity').value);phases=tl.phases;duration=tl.duration;planned=true;$('timeline').max=duration||1;$('moves').textContent=moves.length;$('distance').textContent=(moves.reduce((s,m)=>s+C.length(m.path),0)/1000).toFixed(2)+' m';$('estimate').textContent=duration.toFixed(1)+' s';$('log').innerHTML=moves.map((m,i)=>`<li data-move="${i}">R${m.room+1} · ${m.from===8?'W':'P'+(m.from+1)} → ${m.to===8?'W':'P'+(m.to+1)}</li>`).join('')||'<li>当前布局已经满足目标</li>';audit('plan',{target,velocity:+$('velocity').value,blocked});note(moves.length?`规划成功：${moves.length} 次搬运；等待区最终恢复为空。`:'目标与初始布局一致，无需搬运。');controls();draw();}catch(e){note(e.message,true);}}
  let lastLift=-1;
  function draw(){const st=C.state(initial,phases,time),exp=$('explode').checked?1:0;board.position.y=exp*150;railLayer.position.y=exp*24;bridge.position.set(0,exp*67,300-st.head[1]);carriage.position.x=st.head[0]-400;magnet.position.y=73+20*st.lift;
   if(Math.abs(st.lift-lastLift)>.001){while(servoLink.children.length){const m=servoLink.children[0];m.geometry.dispose();servoLink.remove(m);}const a=[25,87,8],b=[18+st.lift*5,86+st.lift*5,8],c=[0,67+st.lift*20,0];rod(servoLink,a,b,1.5,purple);rod(servoLink,b,c,1,silver);lastLift=st.lift;}
   rooms.forEach((r,i)=>r.position.set(st.positions[i][0]-400,100.5+exp*150,300-st.positions[i][1]));obstacle.visible=$('block').checked;obstacle.position.y=exp*150;guides.visible=!!exp;
   const ghost=$('ghost').checked;boardMat.opacity=ghost?.28:1;boardMat.depthWrite=!ghost;wallMat.opacity=ghost?.14:1;wallMat.depthWrite=!ghost;
   ring.visible=st.active>=0&&!exp;ring.position.set(st.head[0]-400,101,300-st.head[1]);ring.material.color.set(estop?'#c34c37':'#438267');
   const ph=phases.find(p=>time>=p.start&&time<p.end);const routeKey=ph?.type==='drag'?JSON.stringify(ph.path):'';if(routeKey!==lastPhase){if(routeLine){model.remove(routeLine);routeLine.geometry.dispose();routeLine.material.dispose();routeLine=null;}if(routeKey)routeLine=line(model,ph.path.map(([x,y])=>[x-400,102,300-y]),'#377b57');lastPhase=routeKey;}if(routeLine)routeLine.visible=!exp;
   const texts={ready:['准备','选择任务，规划舱段换位'],position:['定位','磁头下降，前往目标舱段下方'],pick:['吸合','抬升磁头，建立隔板牵引'],drag:['拖动','沿无碰撞路径牵引舱段'],drop:['释放','停稳并降低磁头，完成放置'],return:['空返','磁头下降，返回等待区下方'],done:['完成','目标布局已达成，等待区为空']};const title=texts[st.type];$('phasePill').textContent=exp?'结构分层':estop?'急停':title[0];$('caption').textContent=exp?'面板、共享机构与底座的层次关系':title[1];$('captionDetail').textContent=exp?'分层观察期间暂停搬运；关闭分层后可继续。':`当前舱段 ${st.active>=0?'R'+(st.active+1):'—'} · 磁头 X ${st.head[0].toFixed(0)} / Y ${st.head[1].toFixed(0)} mm · ${st.lift>.9?'靠近面板':st.lift<.1?'远离面板':'升降中'}${estop?' · 急停冻结所有动作':''}`;
   $('time').textContent=`${time.toFixed(1)} / ${duration.toFixed(1)} 秒`;$('timeline').value=time;$('completed').textContent=st.finished;[...$('log').children].forEach((e,i)=>e.classList.toggle('current',i===st.finished&&st.type!=='done'));
   const w=stage.clientWidth,h=stage.clientHeight,dist=distance*Math.max(1,1.15/camera.aspect),ty=20+exp*60;camera.position.set(Math.sin(yaw)*Math.cos(pitch)*dist,ty+Math.sin(pitch)*dist,Math.cos(yaw)*Math.cos(pitch)*dist);camera.lookAt(0,ty,0);xPulley.rotation.y=st.head[0]/12;yPulley.rotation.y=st.head[1]/12;
   leds[0].emissiveIntensity=playing?1:.05;leds[1].emissiveIntensity=st.type==='done'?1:.05;leds[2].emissiveIntensity=estop?1:.03;
   renderer.setViewport(0,0,w,h);renderer.setScissorTest(false);renderer.render(scene,camera);const detail=w>800&&['pick','drop'].includes(st.type)&&!exp;detailBox.hidden=!detail;if(detail){detailCamera.position.set(st.head[0]-400+100,112,300-st.head[1]+120);detailCamera.lookAt(st.head[0]-400,88,300-st.head[1]);renderer.setViewport(w-254,130,230,160);renderer.setScissor(w-254,130,230,160);renderer.setScissorTest(true);renderer.render(scene,detailCamera);renderer.setScissorTest(false);}
  }
  $('plan').onclick=compile;$('reset').onclick=()=>{invalidate();note('已恢复初始布局，目标配置保留。');};$('scenario').onchange=e=>{if(presets[e.target.value])setTarget(presets[e.target.value]);invalidate();note('目标已更新，点击规划任务。');};selects.forEach(s=>s.onchange=()=>{$('scenario').value='custom';invalidate();note('每个 R 编号只能出现一次，点击规划任务检查。');});$('block').onchange=()=>{invalidate();note('封闭区已更新，重新规划后自动尝试绕行。');};$('velocity').onchange=()=>{invalidate();note('牵引速度已更新，请重新规划。');};
  $('play').onclick=()=>{if(!planned)return;if(time>=duration)time=0;if(estop){estop=false;audit('release-stop');}playing=!playing;$('explode').checked=false;audit(playing?'play':'pause');controls();draw();};$('stop').onclick=()=>{playing=false;estop=true;audit('emergency-stop');note('已急停：模拟位置保持不变。确认后点击解除急停并继续。',true);controls();draw();};$('step').onclick=()=>{if(estop){note('请先解除急停。',true);return;}playing=false;$('explode').checked=false;time=phases.find(p=>p.end>time+.001)?.end??duration;audit('step');controls();draw();};$('timeline').oninput=e=>{if(estop){e.target.value=time;return;}playing=false;time=+e.target.value;audit('seek');controls();draw();};
  $('explode').onchange=()=>{playing=false;audit('structure-view');controls();draw();};$('ghost').onchange=draw;
  function view(y,p,d=1730){yaw=y;pitch=p;distance=d;draw();}$('viewIso').onclick=$('homeView').onclick=()=>view(.8,.68);$('viewTop').onclick=()=>view(0,1.53,1550);$('viewLow').onclick=()=>view(.5,.24,1500);
  $('present').onclick=()=>{document.body.classList.toggle('presentation');$('present').textContent=document.body.classList.contains('presentation')?'退出路演':'路演模式';resize();};document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.body.classList.remove('presentation');$('present').textContent='路演模式';resize();}if(e.code==='Space'&&!['SELECT','INPUT','BUTTON'].includes(document.activeElement.tagName)){e.preventDefault();if(planned)$('play').click();}});
  let pointer=null;renderer.domElement.addEventListener('pointerdown',e=>{pointer=[e.clientX,e.clientY];renderer.domElement.setPointerCapture(e.pointerId);});renderer.domElement.addEventListener('pointermove',e=>{if(!pointer)return;yaw-=(e.clientX-pointer[0])*.006;pitch=Math.max(.12,Math.min(1.54,pitch+(e.clientY-pointer[1])*.004));pointer=[e.clientX,e.clientY];draw();});for(const event of ['pointerup','pointercancel'])renderer.domElement.addEventListener(event,()=>pointer=null);renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();distance=Math.max(900,Math.min(2600,distance*Math.exp(e.deltaY*.001)));draw();},{passive:false});
  $('export').onclick=()=>{const report={version:'1.0',scope:'geometry-and-sequence-only',initial,target:selects.map(s=>+s.value),velocityMmPerSec:+$('velocity').value,moves,phases,predictedSeconds:duration,current:C.state(initial,phases,time),events,limits:['No magnetic-force or friction model','No lunar environmental or human safety validation']};const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='lunar-simulation-record.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  function resize(){const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();draw();}new ResizeObserver(resize).observe(stage);resize();
  document.addEventListener('visibilitychange',()=>{if(document.hidden){playing=false;controls();}last=performance.now();});
  function frame(now){const dt=Math.min((now-last)/1000,.1);last=now;if(playing){time+=dt*+$('speed').value;if(time>=duration){time=duration;playing=false;audit('complete');note('任务完成，等待区已恢复为空。');if($('loop').checked){time=0;playing=true;audit('loop');}controls();}draw();}requestAnimationFrame(frame);}requestAnimationFrame(frame);
})();
